### ISSUE TITLE
Samller size?

### ISSUE THREAD

**Issue by tunnckoCore** [syntax-tree/hast-util-parse-selector#2]
Hi @wooorm, i'm considering to use that. But bytes matter for my case, so I rewrite it with a minimum characters needed. Each byte is important it will be used in frontend.

around 200-250 bytes smaller.

**Comment by tunnckoCore** [comment]
ES6 bundle would be good too.

**Comment by wooorm** [comment]
@tunnckoCore Oh interesting, could you do a PR for the smaller size?

Re ES6: No, I’m not doing ES6 bundles.

**Comment by wooorm** [comment]
I’ll close the issue here, hope you’ll create the PR!

**Comment by tunnckoCore** [comment]
Okey, I'll send, without the ES6 :)
